apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ainsel.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub-backend
  {{- with .Values.hub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
