apiVersion: v1
kind: Service
metadata:
  name: hub-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ainsel.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.hub.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.hub.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: ainsel-hub-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
