import type {
  Control,
  UseFormRegister,
  UseFormSetValue,
  UseFormWatch,
} from 'react-hook-form'
import { Button } from '../../primitives/Button'
import { Check } from '../../primitives/Check'
import { Field } from '../../primitives/Field'
import { Input } from '../../primitives/Input'
import { Select } from '../../primitives/Select'
import { Tag } from '../../primitives/Tag'
import { Textarea } from '../../primitives/Textarea'
import { ExamplesEditor } from './ExamplesEditor'
import type { ImageFormValues, ToolFormValue } from './ImageDetail.types'

const KIND_OPTIONS = [
  { value: 'shell', label: 'Shell' },
  { value: 'container', label: 'Container' },
] as const

type ToolEditorProps = {
  toolIndex: number | null
  tools: ToolFormValue[]
  control: Control<ImageFormValues>
  register: UseFormRegister<ImageFormValues>
  setValue: UseFormSetValue<ImageFormValues>
  watch: UseFormWatch<ImageFormValues>
  onRemove: () => void
}

export function ToolEditor({
  toolIndex,
  tools,
  control,
  register,
  setValue,
  watch,
  onRemove,
}: ToolEditorProps) {
  if (toolIndex === null || !tools[toolIndex]) {
    return (
      <div className="md-right">
        <header className="md-bar">
          <h4>Tool · select one from the list</h4>
          <div className="md-bar-grow" />
        </header>
        <div className="tool-empty">No tool selected.</div>
      </div>
    )
  }

  const tool = tools[toolIndex]
  const kindValue = watch(`tools.${toolIndex}.kind`)
  const isMCP = tool.kind === 'mcp'

  // MCP tools are auto-generated by the Refresh button — show read-only.
  if (isMCP) {
    return (
      <div className="md-right">
        <header className="md-bar">
          <h4 title={tool.name} style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>Tool · {tool.name || `#${toolIndex + 1}`}</h4>
          <div className="md-bar-grow" />
          <Tag>mcp</Tag>
        </header>
        <div className="tool-detail">
          <div className="tool-state">
            <Check
              aria-label="enabled"
              checked={tool.enabled}
              onChange={(next) => setValue(`tools.${toolIndex}.enabled`, next, { shouldDirty: true })}
            />
            <span className="tool-state-text">
              {tool.enabled ? 'Enabled' : 'Disabled'}
            </span>
            <span className="label tool-state-spacer">{tool.mcpSource} MCP</span>
          </div>

          <div className="tool-fqn">{tool.name}</div>

          <p className="tool-hint">
            MCP tools are auto-populated by the <b>Refresh MCP Tools</b> button. Edit the MCP
            server configuration to change which tools appear here.
          </p>
          {tool.description ? (
            <Field label="Description" htmlFor="">
              <div className="tool-readonly">{tool.description}</div>
            </Field>
          ) : null}
        </div>
      </div>
    )
  }

  return (
    <div className="md-right">
      <header className="md-bar">
        <h4>Tool · {tool.name || `#${toolIndex + 1}`}</h4>
        <div className="md-bar-grow" />
        <Button size="sm" variant="danger" onClick={onRemove}>
          Remove
        </Button>
      </header>
      <div className="tool-detail">
        <div className="tool-state">
          <Check
            aria-label="enabled"
            checked={tool.enabled}
            onChange={(next) => setValue(`tools.${toolIndex}.enabled`, next, { shouldDirty: true })}
          />
          <span className="tool-state-text">
            {tool.enabled ? 'Enabled' : 'Disabled'}
          </span>
        </div>
        <div className="tool-title">
          <h2>{tool.name || <em>unnamed</em>}</h2>
          <Tag>{tool.kind}</Tag>
        </div>

        <div
          style={{ display: 'grid', gridTemplateColumns: '1fr 220px', gap: 14, marginBottom: 18 }}
        >
          <Field label="Name" htmlFor={`tool-name-${toolIndex}`}>
            <Input
              id={`tool-name-${toolIndex}`}
              placeholder="run_shell"
              {...register(`tools.${toolIndex}.name`)}
            />
          </Field>
          <Field label="Kind" htmlFor={`tool-kind-${toolIndex}`}>
            <Select
              id={`tool-kind-${toolIndex}`}
              value={kindValue}
              onChange={(v) =>
                setValue(
                  `tools.${toolIndex}.kind`,
                  v as ToolFormValue['kind'],
                  { shouldDirty: true },
                )
              }
              options={KIND_OPTIONS}
            />
            <input type="hidden" {...register(`tools.${toolIndex}.kind`)} />
          </Field>
        </div>

        <Field
          label="Description (markdown)"
          htmlFor={`tool-description-${toolIndex}`}
        >
          <Textarea
            id={`tool-description-${toolIndex}`}
            rows={6}
            placeholder="What does this tool do? When should an agent reach for it?"
            {...register(`tools.${toolIndex}.description`)}
          />
        </Field>

        <header className="tool-subhead">
          <h4>Examples · {tool.examples?.length ?? 0}</h4>
        </header>
        <ExamplesEditor control={control} register={register} toolIndex={toolIndex} />
      </div>
    </div>
  )
}
