apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-ai-agent-operator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ainsel.labels" . | nindent 4 }}
    app.kubernetes.io/component: k8s-ai-agent-operator
  {{- with .Values.agentOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
