{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ainsel.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6333
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: ainsel-qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
